syntax = "proto3";

package calendar.grpc;

option java_multiple_files = true;
option java_package = "ru.otus.vinakov.calendar.grpc";

service CalendarCalculationGrpcService {
  rpc calculateDate(DateCalculationGrpcRequest) returns (DateCalculationGrpcResponse);
  rpc calculateDuration(DurationCalculationGrpcRequest) returns (DurationCalculationGrpcResponse);
}

message LocalDateTimeMessage {
  int32 year = 1;
  int32 month = 2;
  int32 day = 3;
  int32 hour = 4;
  int32 minute = 5;
  int32 second = 6;
}

message WorkPeriodMessage {
  uint32 start_hour = 1;
  uint32 start_minute = 2;
  uint32 end_hour = 3;
  uint32 end_minute = 4;
}

message DateCalculationGrpcRequest {
  string calendar_key = 1;
  LocalDateTimeMessage start_date = 2;
  int64 duration = 3;
  string timezone = 4;
  repeated WorkPeriodMessage periods = 5;
}

message DateCalculationGrpcResponse {
  LocalDateTimeMessage date = 1;
  string timezone = 2;
}

message DurationCalculationGrpcRequest {
  string calendar_key = 1;
  LocalDateTimeMessage start_date = 2;
  string start_timezone = 3;
  LocalDateTimeMessage end_date = 4;
  string end_timezone = 5;
  repeated WorkPeriodMessage periods = 7;
}

message DurationCalculationGrpcResponse {
  int64 duration = 1;
}